default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost        # Forcing TCP helps avoid Peer auth issues
  port: 5432
  username: employee_mgmt
  password: '1234'       # Ensure this matches what you set in psql
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: employee_mgmt_development

test:
  <<: *default
  database: employee_mgmt_test


production:
  primary: &primary_production
    <<: *default
    database: employee_mgmt_production
    username: employee_mgmt
    password: <%= ENV["EMPLOYEE_MGMT_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: employee_mgmt_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: employee_mgmt_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: employee_mgmt_production_cable
    migrations_paths: db/cable_migrate
